name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  
  test-env:
    name: Printing out Env-variables
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: env
